### PR TITLE
Adding support for linux mint

### PR DESCRIPTION
**Pull request by Skypodo**
See #35 for details.

### CODE REVIEW

**Review by MatiAtMicrosoft — CHANGES_REQUESTED** [review]
Thank you for contributing.
Unfortunately this change breaks the entire script.
A better change will keep DISTRO as ID and would mark _mint_ as one of the supported distros.

BTW, mint os not officially supported, so MS cannot guarantee that the full set of features would work seamlessly.

**Comment by Skypodo** [comment]
I reworked my changes. This way it should no longer break the script.

**Review by MatiAtMicrosoft — APPROVED** [review]
Approving the change.
Will move lines 292-296 to before 282, so the change in 282 will not be needed.

**Comment by agarwalneetu** [comment]
Hi @Skypodo, can I go ahead and close this issue #35 ?

**Comment by Skypodo** [comment]
Yes, you can. Sorry, I kinda forgot about it.

**Comment by agarwalneetu** [comment]
Np, seems like I can't close this issue. if you can, please close it.

**Pull request merged**
