### PR TITLE
Fix typo in background services config

### PR DESCRIPTION
**Pull request by RedVortex**
Simple typo fix

### CODE REVIEW

**Comment by RedVortex** [comment]
@maximvelichko Can you have a look at this. Simple minor typo correction but it shows in the profiles in the MacOS Profiles section once loaded. Thank you.

**Comment by maximvelichko** [comment]
Thank you @RedVortex !

**Comment by RedVortex** [comment]
@maximvelichko I thought the combined profiles auto-updated on commit but I was mistaken. Should I update the combined files as well to fix the typo there also ? Sorry about the troubles :-/

**Comment by maximvelichko** [comment]
No worries, I build combined profiles with macos/mobileconfig/combined/build.sh script, and commit them manually.
Done.

**Pull request merged**
